### PR TITLE
[deno] Fix/542 fix updates after feedback

### LINKED ISSUE #542: [deno] Make necessary updates after feedback
This was Dustin's feedback on deno.framework.dev:

- [x] The sub-categories for libraries don't really make sense for Deno. They're customizable and should be updated. See the [node.js/graphql](http://node.js/graphql) site implementation for an example of how you can update.
- [x] The list of general conferences we used on the angular/vue/react site for communities was not added to this site and needs to be: [https://docs.google.com/spreadsheets/d/1jGZyAFVS4Z8rWwZJ1J_aqRk6JY5pfOutFlLBv7-nqUU/edit#gid=0 - Connect to preview](https://docs.google.com/spreadsheets/d/1jGZyAFVS4Z8rWwZJ1J_aqRk6JY5pfOutFlLBv7-nqUU/edit#gid=0)
- [x] If there are any Deno meetups (state of), those should be added
- [x] Modern Web is missing from podcasts
- [x] This Dot Blog is missing from blogs
- [x] Comparison doesn't work for Deno because they aren't on the npm registry. Is there anything we can do to solve this or do we need to disable this feature on this site?
- [x] Set up Google Analytics: G-NWSVDGBF27

### PR DESCRIPTION
**Pull request by dariodjuric**
Closes #542.

### CODE REVIEW

File: packages/site/src/data/search-data.ts [hunk 1]
```diff
@@ -20,24 +20,37 @@ export async function getSearchData(
 	const { podcasts, podcastTags } = await import(`./${framework}/podcasts.js`)
 	const { tools, toolTags } = await import(`./${framework}/tools.js`)
 
+	let librarySubCategories = [
```
Comment (dariodjuric) [inline packages/site/src/data/search-data.ts:23]: @WillHutt does this change look OK to you?

I added subcategories for Deno.

**Review by vyktoremario — APPROVED** [review]
