### PR TITLE
Fix/389 missing hero images

### LINKED ISSUE #389: [BUG] Broken images showing in hero sections for the Qwik and SolidJS sites
**Describe the bug**
On the homepage for both the Qwik and SolidJS sites, there is a  broken image sitting on top of the hero section image.

**To Reproduce**
1. Go to [framework.dev](https://pr-388.d27jqwpr7xbhbg.amplifyapp.com/)
2. Click on either the [Qwik](https://qwik.framework.dev/) or [Solidjs](https://solidjs.framework.dev/) resources
3. See the error where there a broken image sitting on top of the hero section image

**Expected behavior**
no broken images should display

**Screenshots**
Screen Shot 2022-10-31 at 9 56 44 AM

Screen Shot 2022-10-31 at 9 56 56 AM

### PR DESCRIPTION
**Pull request by morgnism**
## Type of change

- [ ] Content addition
- [ ] Bug fix
- [x] Behavior change

## Summary of change

Updates the following:
- solidjs primary theme colour pallet to match primary colour in figma
- fix hero banner image
- fix missing solidjs framework hero and sidebar logos
- enable the site on the landing page
- adjust landing page columns to display a max of 4 frameworks per row

## Checklist

- [x] This change resolves #389 
- [x] I have confirmed with a maintainer that this change is desired and been
      given the go-ahead to work on it in the relevant issue discussion
- [x] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [x] I have verified the change and the rest of the site works as expected

image

image

### CODE REVIEW

**Comment by morgnism** [comment]
Raised primary colour pallet discrepancies with @dustinsgoodman. Blocking until then.

File: packages/system/src/globals/global-constants.tsx [hunk 1]
```diff
@@ -33,15 +33,15 @@ export const FRAMEWORK_RESOURCES = (bigSize = false): LinkCardProps[] => [
...
-	// 	backgroundColor: "#2c4f7c",
-	// 	bigSize,
-	// 	},
+	{
+		title: "SolidJS Resources",
+		href: "https://solidjs.framework.dev/",
+		Icon(props) {
+			return <SolidJSIcon {...props} />
+		},
+		backgroundColor: "#2B4E8B",
```
Comment (dustinsgoodman) [inline packages/system/src/globals/global-constants.tsx:42]: Change this to 446b9e

**Review by dustinsgoodman — APPROVED** [review]
